### ISSUE TITLE
Advanced Search Changes

### ISSUE THREAD

**Issue by frankwiles** [revsys/revsys-nuremberg#119]
- [x] Add Year Date Range to form
- [x] ~Convert Advanced Search to React~
- [x] Remove 'Advanced Search' link in upper right hand corner when on Advanced search page as it's confusing
- [x] Hide the advanced search form itself once the user has submitted
- [x] Add 'Clear Form' button to blank out the form
- [x] Change label to be "Match all entered search terms below"
- [x] Change "Keyword" input to NOT do exact phrase as it is now

**Comment by frankwiles** [comment]
@nessita I think you may have already handled a few of these if I'm not mistaken? Or am I wrong?

**Comment by nessita** [comment]
@frankwiles I only solved the last item which I'm now marking as Completed, the first 5 are still pending

**Comment by frankwiles** [comment]
Adjust advanced search button placement 
![advanced_search_feedback_3](https://user-images.githubusercontent.com/144159/221281758-96680a52-2211-4b6a-808c-56ae06084b40.jpg)

**Comment by pdeschner** [comment]
Advanced search form should exist alone on page -- not sit above previous search results.

![advanced_search_form_alone_on_page](https://user-images.githubusercontent.com/1544067/225150403-870f59ed-6634-4909-95c2-8084359af752.jpg)

**Comment by frankwiles** [comment]
Move the search buttons!
