### ISSUE TITLE
Author hover UI

### ISSUE THREAD

**Issue by frankwiles** [revsys/revsys-nuremberg#12]
Make it like wikipedia hover over links.  

On smaller screens (especially mobile phones), it may be best to take over the whole screen and have a close button. 

On larger screens, it should disappear when no longer hovering over it.

**Comment by frankwiles** [comment]
Where data is injected https://github.com/revsys/revsys-nuremberg/blob/main/web/nuremberg/search/views.py#L152

**Comment by frankwiles** [comment]
Ok I've improved this a bit.  Should probably verify it is ok on mobile.

**Comment by frankwiles** [comment]
Small issue on mobile left, but nearly done.

**Comment by nessita** [comment]
Some issues for the current deployed version (one comment per issue):

1- When looking at author fly-out for a document page (for example https://nuremberg.revsys.dev/documents/453258), the author fly-out box has the document image controls shown on top of the box, this seems like a "stacking" issue. Screenshot:
![Screenshot_20230224_091250](https://user-images.githubusercontent.com/124304/221176707-c88b2917-0338-4c35-bb07-6a6487b31dca.png)

**Comment by frankwiles** [comment]
Good catch on both of these, I had only see the author fly out on the search results page and hadn't noticed it was also used on the Document page.  

I'm breaking the second issue off into another ticket as it needs to be handled when I get to the JS on that page.
