### ISSUE TITLE
Document "Missing Image" CSS potentially broken

### ISSUE THREAD

**Issue by nessita** [revsys/revsys-nuremberg#136]
There seems like the CSS for the missing images placeholder for documents may be broken or buggy. See for example https://nuremberg.law.harvard.edu/documents/2683#p.1 which looks like this:

![image](https://user-images.githubusercontent.com/124304/211827564-6b0da418-b24d-4345-bfb7-0a434573ad11.png)

In the dev site, this same doc https://nuremberg.revsys.dev/documents/2683#p.1 looks like this:

![image](https://user-images.githubusercontent.com/124304/211827721-2cf59a12-f887-4751-93ec-77860618e8c6.png)

**Comment by frankwiles** [comment]
@nessita is this perhaps because we now have an image for this document in the local dev database, from the new dumps, and so it isn't rendering the "missing" bit and I just have uploaded the new images to S3 yet?

**Comment by nessita** [comment]
So I don't think that's the case, there is something about width and height which are set to 700x1000 in the original site even if there is no image for it. See the diffs in the HTMLs (this is current vs original):

```diff
           <div class="document-image-layout"><div style="display: inline-block; width: 0px; height: 1px;"></div>


-                <div data-screen-url="None" data-thumb-url="" data-full-url="" data-width="None" data-height="None" class="document-image image-missing loading current" data-page="1" style="width: Nonepx; height: Nonepx;" data-alt="Document page 1">
+                <div data-screen-url="None" data-thumb-url="" data-full-url="" data-width="700" data-height="1000" class="document-image image-missing loading hidden" data-page="1" style="width: 700px; height: 1000px;" data-alt="Document page 1">

                     <div class="image-label">
                       Missing Image No. 1
                     </div>

-                <img alt="Document page 1" src="None"><div class="aspect-ratio-spacer"></div></div>
+                <img style="border-bottom-width: 7.14286px;" alt="Document page 1" src="None"><div class="aspect-ratio-spacer" style="margin-top: 142.857%;"></div></div>

-                <div data-screen-url="None" data-thumb-url="" data-full-url="" data-width="None" data-height="None" class="document-image image-missing loading" data-page="2" style="width: Nonepx; height: Nonepx;" data-alt="Document page 2">
+                <div data-screen-url="None" data-thumb-url="" data-full-url="" data-width="700" data-height="1000" class="document-image image-missing loading current" data-page="2" style="width: 700px; height: 1000px;" data-alt="Document page 2">

                     <div class="image-label">
                       Missing Image No. 2
                     </div>

-                <img alt="Document page 2"><div class="aspect-ratio-spacer"></div></div>
+                <img style="border-bottom-width: 7.14286px;" alt="Document page 2" src="None"><div class="aspect-ratio-spacer" style="margin-top: 142.857%;"></div></div>


           </div>
```

I'll dig some more and update the issue

**Comment by nessita** [comment]
I don't see code setting width and height to 700x1000 anywhere.

Seems like at some point this was added to the DB manually. I grabbed an old dump, the latest in Dec 2022, and found out that width and height are effectively set to 700x1000:

```
sqlite> SELECT * FROM documents_documentimage WHERE document_id=2683;
id|page_number|physical_page_number|url|scale|width|height|document_id|image_type_id|image
32228|1|51||s|700|1000|2683|1|
32238|2|52||s|700|1000|2683|1|
```
More broadly, every DocumentImage with a null url has width and heigth set to 700x1000:
```
sqlite> SELECT COUNT(*) FROM documents_documentimage WHERE url is NULL;
COUNT(*)
35

sqlite> SELECT COUNT(*) FROM documents_documentimage WHERE url is NULL and width != 700 and height != 1000;
COUNT(*)
0
```

@frankwiles I will have the template default to 700x1000 and see if that fixes it.

**Comment by nessita** [comment]
Update: I've landed this commit https://github.com/revsys/revsys-nuremberg/commit/64e2dc6ef642a0aefa889afc717a0b5b1041d28a and while this improves the visual of the spacing, there is still something odd. I have narrowed it down to a piece of javascript  (backbone's `images.js` file) being run that would add an `<img>` tag like this:

```html
<img style="border-bottom-width: 7.14286px;" alt="Document page 1" src="data:text/html;base64,Cgo8IWRvY3R5...sPgo=">
<div class="aspect-ratio-spacer" style="margin-top: 142.857%;"></div>
```

**Comment by nessita** [comment]
This was solved with the referenced commit.
