### ISSUE TITLE
Link to the advanced search help page from somewhere

### ISSUE THREAD

**Issue by nessita** [revsys/revsys-nuremberg#153]
The advanced search help page is available after https://github.com/revsys/revsys-nuremberg/pull/137 was landed, but we need to link it from somewhere.

**Comment by nessita** [comment]
@pdeschner Could you comment on this issue to confirm where the search help page should be linked from?

**Comment by pdeschner** [comment]
Substitute "Search Tips" for current "Advanced Search" link at upper right of advanced-search page

![search_tips_link_on_advanced_search_page](https://user-images.githubusercontent.com/1544067/229779851-a52ae992-801e-4be6-937c-abb0a2c19ec7.jpg)
