### ISSUE TITLE
Paul request: Standardize the materials-type icons used in the app

### ISSUE THREAD

**Issue by nessita** [revsys/revsys-nuremberg#194]
From Paul:

I'd like to standardize the materials-type icons used in the app.  Currently, we use one set of icons in the "Access the Collection" section of the landing page and an entirely different set inside the application.  I'd like to completely dispense with the icons in the Access the Collection section and use the ones from the interior of the application for transcripts and photographs and the attached new one for documents.  I'd also like to substitute the new document icon for the one currently being used inside the app, the latter of which is more suggestive of a folder than a document.  I'm using a public domain version of the new document icon.

The icon image:
![doc_icon](https://user-images.githubusercontent.com/124304/221177363-ad21cad9-80b8-4157-a60e-4e9c7f93e8c5.jpg)

Places where it should be replaced:
![icon_doc_change_inside_app](https://user-images.githubusercontent.com/124304/221177443-9dd7aa02-c4d5-4ae0-91f6-81e9f8bfcd60.jpg)
![icons_changed_on_landing_page](https://user-images.githubusercontent.com/124304/221177453-c3a6b050-1655-4382-aa6e-f6f6a40f5462.jpg)

**Comment by frankwiles** [comment]
Updated, now looks like this: 

![CleanShot 2023-06-07 at 14 46 37](https://github.com/revsys/revsys-nuremberg/assets/144159/42f61682-ccc6-41e8-be5f-e3c35c044cab)

**Comment by pdeschner** [comment]
These icons need to be standardized in 2 places:
1. Landing page
2. Search results

They've only been standardized on the landing page so far
