### ISSUE TITLE
Query string overruns "x" icon at right of query box

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#205]
Query box's "x" at far right should be protected by padding from being overlapped by extended query string

![extended_query_overlap_in_query_box](https://user-images.githubusercontent.com/1544067/225109921-9be701af-a970-4416-a400-2b303b86c904.jpg)

**Comment by frankwiles** [comment]
Instead of fixing this CSS issue: 

- [ ] Remove X from input box
- [ ] Add Clear button to the right of search
