### ISSUE TITLE
Full-text transcript search: snippet results text content extending beyond right page edge

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#207]
In some cases, text content extends beyond edge of page on right

![content_bleed_over_right-hand_page_edge](https://user-images.githubusercontent.com/1544067/225129163-989d5a1c-f7a6-4bb1-b129-d8183a69ead2.jpg)

**Comment by pdeschner** [comment]
![content_bleed_over_right-hand_page_edge_2](https://user-images.githubusercontent.com/1544067/227360859-816f1020-8cf2-431f-be25-aabbe6ef0781.jpg)

**Comment by nessita** [comment]
cc @frankwiles 
I haven't investigated yet the root cause for this issue but I've noticed this is also happening in the original site. See for example:
* https://nuremberg.revsys.dev/search/?q=annexed
* https://nuremberg.law.harvard.edu/search/?q=annexed

**Comment by frankwiles** [comment]
I see it on the old site now and not the new dev site, so I assume this was fixed as I was working on something semi-related.
