### ISSUE TITLE
Fields with null values should not display in document metadata viewer

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#209]
Fields with null values should not display in document metadata viewer

![null_values_should_suppress_associated_fields](https://user-images.githubusercontent.com/1544067/225152497-d72c98a9-6f1c-484a-806b-c24f9a29df6f.jpg)

**Comment by nessita** [comment]
cc @frankwiles 
I haven't investigated yet the root cause for this issue but I've noticed this is also happening in the original site. See for example:
* https://nuremberg.revsys.dev/documents/19
* https://nuremberg.law.harvard.edu/documents/19

**Comment by pdeschner** [comment]
Would one possible approach here be to simply filter out (or suppress the display of) any document field returned by Solr which isn't populated.

**Comment by frankwiles** [comment]
Yeah we can definitely hide empty fields

**Comment by frankwiles** [comment]
Actually this IS hiding the empty fields for a lot of these items, but in this case there DOES EXIST an Exhibit Code (primary key = 7) that does not have a prosecution_number or defense_number so when it's turned into a string for display it's just a blank empty string. 

I could change that to be some other string like 'UNKNOWN' for the fall through case there if you want.

**Comment by pdeschner** [comment]
Not sure I follow.  Are we talking about HLSL item no. 19 in the screenshot above?  If so, in tblCasesList, doc ID 19 (equals HLSL item no.) has only NULL values populating all exhibit values (for both prosecution and defense).  Not sure what primary key you're speaking of?

At any rate, any empty string will be equivalent to a NULL value in our db, I think.  So, if it were encountered, both it and its associated field could be suppressed?

**Comment by frankwiles** [comment]
Resolved this be checking the codes for values.
