### ISSUE TITLE
Metadata search: hlsl item number false positives

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#219]
HLSL item number search retrieves false positives

![metadata_search_hlsl_item_number_false_positive](https://user-images.githubusercontent.com/1544067/227333240-aff227a9-19d7-49e6-8c59-b71f958cd74f.jpg)

![metadata_search_hlsl_item_number_false_positive_2](https://user-images.githubusercontent.com/1544067/227333271-5dde1339-3e93-44af-b25a-8997f953e821.jpg)

**Comment by nessita** [comment]
cc @frankwiles 
This is another issue part of the group "Solr backend specific behavior that is also present in the original site". Adding the proper label and flagging Frank to decide next steps.

Reference URLs:
* https://nuremberg.law.harvard.edu/search/?q=hlsl%3A7607
* https://nuremberg.law.harvard.edu/search/?q=hlsl%3A7607

**Comment by pdeschner** [comment]
Would not one possible approach here be to add some business logic to the backend which would filter out all the documents returned by Solr which do not contain an HLSL item no. matching that of the query.  There should only ever be a single document per requested HLSL item no. in the search query.

**Comment by pdeschner** [comment]
I'm flying a little blind here, since I don't know how we're interfacing with Solr.  I think I was assuming that the response object for a document from Solr would somehow be structured with key-value pairs for the object, with each populated key being a metadata field displayed in the metadata panel of the document page on the website, or something similar.  If so, then I thought one could simply test for the presence of the "hlsl" key in each returned document object, and then ignore all the documents without an hlsl key.  My assumption is that there would only ever be a single document object returned for a given hlsl query, since the hlsl no. is a unique identifier in our project.  What am I missing here?

**Comment by frankwiles** [comment]
So in general search engines don't work like a database is the main thing to keep in mind.  They're looking for fuzzy matches of things and then ranking them by "closest" matches.  

The rough mental model is: 

- take the query from the User and POST it as JSON to a Solr API endpoint
- Solr endpoint returns a JSON object of results of things that matched with the data we push into Solr associated with it

So you are sort of right, in that we can look for an "HLSL" key, in either Solr or the DB, to get a single exact match like that but have to bail out and just let Solr do it's thing if they were instead searching for "hlsl-88 camp" or anything not JUST an single value like that.  Or at least for some small subset of values we hard code to have meaning. 

Does that make more sense?

**Comment by pdeschner** [comment]
But isn't the original issue documented here only if the user is explicitly entering the syntax "hlsl:5607" (or whatever number they want).  The hlsl item no. is not a keyword search (as in your example "hlsl-88 camp"), but a fielded search.  And the search result in that case would only ever be a single result at best regardless of what else is in the search request, since only one document can ever have that hlsl item no.  It's possible that no results returned by Solr would have that hlsl item no., either because there are no documents in our current collection with that ID or because the other search conditions (e.g., "hlsl:5607 hitler monkeys") could not be met within a document satisfying that hlsl item no.

For example, the search "hlsl:451103 ghetto" -- a hybrid search containing a fielded query on the key "hlsl" and a keyword qurey on string "ghetto" -- produces a single result because we have that hlsl item no. in our collection, and its full text contains the string "ghetto."  But "hlsl: 451103 monkeys" would not return a result because the string "monkeys" is not contained in the text.  Wouldn't filtering on the hlsl key in the Solr JSON response get us what we need?

**Comment by frankwiles** [comment]
ok I dug back into this one and figured out the issue.  

The way the system is written `hlsl` is the Django database ORM object primary key value.  `7607` in this specific case.  The results here are: 

- Document PK 7607
- Transcript Page PK 7607

So it's doing what we asked, but not ideal.  @pdeschner should we make the keyword `hlsl` be `Document` specific and ignore the PKs on other types of database entries?

**Comment by pdeschner** [comment]
Yes, hlsl:\d+ entered as search should always only return the material type "document"

**Comment by frankwiles** [comment]
Fixed with a real hlsl search field change.
