### ISSUE TITLE
Full-text transcript search: incorrect hit counts indicated

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#221]
Full-text search: hit counts incorrect for both single-term and exact-phrase searches

![full-text_incorrect_hit_counts_4](https://user-images.githubusercontent.com/1544067/227357082-af3d2663-ef9e-43a6-93b2-9c63e1583589.jpg)

![full-text_incorrect_hit_counts_3](https://user-images.githubusercontent.com/1544067/227356516-c11cf4da-6f93-4da1-8a10-cf7a7a8c6255.jpg)

![full-text_incorrect_hit_counts_2](https://user-images.githubusercontent.com/1544067/227356518-d62f52e8-290c-4a9a-ba69-9aa933600fdc.jpg)

![full-text_incorrect_hit_counts](https://user-images.githubusercontent.com/1544067/227353006-36ceedfe-6da8-44e8-b90f-1e7e9485f619.jpg)

**Comment by nessita** [comment]
cc @frankwiles 
This is another issue part of the group "Solr backend specific behavior that is also present in the original site". Adding the proper label and flagging Frank to decide next steps.

Reference URLs:
* https://nuremberg.revsys.dev/search/?q=%22the%20question%22
* https://nuremberg.law.harvard.edu/search/?q=%22the+question%22

**Comment by frankwiles** [comment]
These also seem to be fixed now.
