### ISSUE TITLE
Full-text transcript search: exact phrase false positives via stemming matches

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#222]
In full-text search, matching based on stem matches should not be allowed.

![full-text_exact_phrase_not_matched_3](https://user-images.githubusercontent.com/1544067/227364313-bfd60c5c-a3d8-4577-82ea-023543b6e8a8.jpg)

![full-text_exact_phrase_not_matched_2](https://user-images.githubusercontent.com/1544067/227364314-ed7b7a69-e8f6-4aca-94e6-74cd786adb2f.jpg)

![full-text_exact_phrase_not_matched](https://user-images.githubusercontent.com/1544067/227364317-fcac8226-6b51-4f6a-889c-7c58e682830c.jpg)

**Comment by nessita** [comment]
cc @frankwiles 
This is another issue part of the group "Solr backend specific behavior that is also present in the original site". Adding the proper label and flagging Frank to decide next steps.

Reference URLs:
* https://nuremberg.revsys.dev/search/?q=%22battalion+commander%22
* https://nuremberg.law.harvard.edu/search/?q=%22battalion+commander%22

**Comment by frankwiles** [comment]
This is a bit better without stemming, but not perfect @pdeschner.  Not sure if you want to close this or leave it open.
