### ISSUE TITLE
Full-text transcript exact-phrase search: ellipsis incorrectly separating terms of phrase

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#223]
In full-text exact-phrase query, ellipsis incorrectly separates terms of exact phrase, instead of separating snippet instances of exact phrase found in the document

![full-text_exact_phrase_ellipsis_issue](https://user-images.githubusercontent.com/1544067/227365875-aa49edd7-f053-4dbd-af66-2e99aefa5465.jpg)

![full-text_exact_phrase_ellipsis_issue_2](https://user-images.githubusercontent.com/1544067/227367002-a3590669-9a9f-47f2-bfb5-3991ef28e774.jpg)

**Comment by pdeschner** [comment]
![full-text_transcript_highlighting_correct_in_transcript_page](https://user-images.githubusercontent.com/1544067/227629744-68009875-1952-4547-bdfc-4d0f1b1a495b.jpg)

![full-text_exact_phrase_ellipsis_issue_3](https://user-images.githubusercontent.com/1544067/227628299-4705b851-f0e0-4a6c-9fa3-5dc6e5ce2009.jpg)

**Comment by nessita** [comment]
cc @frankwiles 
This is another issue part of the group "Solr backend specific behavior that is also present in the original site". Adding the proper label and flagging Frank to decide next steps.

Reference URLs:
* https://nuremberg.revsys.dev/transcripts/4-transcript-for-nmt-7-hostage-case/search?q=%22i+was+not+there+at+all%22&page=2
* https://nuremberg.law.harvard.edu/transcripts/4-transcript-for-nmt-7-hostage-case/search?q=%22i+was+not+there+at+all%22&page=2

**Comment by frankwiles** [comment]
Look into why an ellipsis is getting INSERTED into the middle of this text.  The full text "I was not there at all" does exist in the Transcript, not sure why the snippet is adding that in as there is nothing in between.

**Comment by frankwiles** [comment]
Also, look into the counts roll up. The aggregation of the Transcript hit counts is wrong, like way off.  But the underlying Transcript page is correct see if there is a bug in adding those when they do the fancy concatenation on the results page.
