### ISSUE TITLE
Transcript page image view link not working

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#228]
When user clicks on View link in transcript page viewer, the page image does not come up.  This is working in the legacy site.

![transcript_page_image_link_not_working](https://user-images.githubusercontent.com/1544067/228341702-5dd8f3ae-9e4d-4388-9d9d-cbbafa34671f.jpg)

**Comment by nessita** [comment]
@frankwiles The current HTML for [the transcript joined pages](https://github.com/revsys/revsys-nuremberg/blob/main/web/nuremberg/transcripts/templates/transcripts/joined_pages.html) has no "logic" in the `<a>` tag:

```html
              {% if page.image_url %}
                  <span class="image-options">
                      - Image
                      [<a class='view-image'>View</a>]
                      [<a class='download-image' href="{{ page.image_url }}" download="Transcript Seq {{ page.seq_number }}.jpg">Download</a>]
                  </span>
              {% endif %}
```

The functionality for the "View" link within the transcript pages was provided via [this piece of Javascript code](https://github.com/revsys/revsys-nuremberg/blob/main/web/nuremberg/transcripts/static/scripts/transcripts.js#L231):

```js
  $viewport.on('click', 'a.view-image', function (e) {
    var $handle = $(this).closest('.page-handle')
    var href = $handle.find('.download-image').attr('href');
    if (!$handle.hasClass('has-image')) {
      $handle
      .addClass('has-image')
      .after('<div class="page-image hide"><img src="'+ href +'" /></div>');
    }
    $img = $handle.next('.page-image');
    $img.toggleClass('hide');
    if ($img.hasClass('hide')) {
      $handle.removeClass('show');
      $handle.find('a.view-image').text('VIEW');
    } else {
      $handle.addClass('show');
      $handle.find('a.view-image').text('HIDE');
    }
    e.stopPropagation();
  });

  $viewport.on('click', '.page-handle', function () {
    $(this).addClass('show');
  });
```

I'm assigning this back to you to confirm whether this would be incorporated to the new JS code, or if you had other idea in mind.
