### ISSUE TITLE
Full-text View Link for documents often not working, resulting in error: "502 Bad Gateway"

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#230]
When user clicks on "Full-text View" link in document image view, often (not always) the link doesn't execute, timing out with error: "502 Bad Gateway"

![full-text_doc_link_not_working](https://user-images.githubusercontent.com/1544067/228365350-284781e1-506a-432b-812e-470272f4d037.jpg)

![full-text_doc_link_not_working_bad_gateway_message](https://user-images.githubusercontent.com/1544067/228365374-577fdb08-9698-4845-8fce-c85170967681.jpg)

**Comment by frankwiles** [comment]
Transient issue related to a deploy.
