### ISSUE TITLE
User clicks on full-text document in search-results listing: full-text display should be default, not image view

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#237]
When the user clicks on a full-text document in the search-results listing, they should be taken to the full-text display of the document, not to the image view, as the default view

![full-text_search-results_listing_should_default_to_full-text_display](https://user-images.githubusercontent.com/1544067/228968217-cc43a986-0d6f-47ca-b603-73b5d19d0af1.jpg)

![full-text_search-results_listing_should_default_to_full-text_display_2](https://user-images.githubusercontent.com/1544067/228968239-61b1aaf4-b788-4879-b72a-00e125aaf316.jpg)

**Comment by frankwiles** [comment]
Include the related Document Image and Document Text in the `search_indexes.py` so we can always take them to the text version of things.
