### ISSUE TITLE
Full-text document search: false positives via stemming

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#240]
In full-text document search, false positives returned via stemming rather than exact literal matches

![full-text_document_false_positive_via_stemming](https://user-images.githubusercontent.com/1544067/229635874-61210673-08f0-4fd5-907a-9e7c80221988.jpg)

![full-text_document_false_positive_via_stemming_2](https://user-images.githubusercontent.com/1544067/229635891-c9f91074-a16f-4805-80e4-5e148b8f6307.jpg)

**Comment by frankwiles** [comment]
@pdeschner I have a non-stemmed version running locally.  If I search for both of these now I can zero results for example: 

![CleanShot 2023-06-12 at 15 56 30](https://github.com/revsys/revsys-nuremberg/assets/144159/87302abe-4bcb-4f12-b457-8f478f2dcb72)

Whereas if I search for "we proceed" vs "we proceeds" I get this: 
![CleanShot 2023-06-12 at 15 57 15](https://github.com/revsys/revsys-nuremberg/assets/144159/8db5b009-9b4e-4366-a8ff-152629e33798)

vs empty results for the plural exact: 

![CleanShot 2023-06-12 at 15 57 45](https://github.com/revsys/revsys-nuremberg/assets/144159/9b53f6bd-96b6-46b7-a74a-538f23130285)

Is that more the behavior you are looking for?

**Comment by pdeschner** [comment]
Yes, exact matching only is what we're interested in testing.  Would there be an instance I could try out?

Thanks,

Paul

________________________________
