### ISSUE TITLE
Full-text document search: matched-string count missing in search results

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#241]
In full-text document search, the matched-string count is missing from the search results (this is present in the transcript search results)

![full-text_documents_matched_string_count_missing_in_results](https://user-images.githubusercontent.com/1544067/229637463-08f151f1-6ca7-4981-8ac6-6c351e54c1f0.jpg)

**Comment by pdeschner** [comment]
[Please see full-text spec, item 4.](https://docs.google.com/document/d/1aZwttEhQASMA-ukm36URMtORRYgWkzQb5wOgFa8TFPk/edit?usp=sharing)

**Comment by frankwiles** [comment]
Fixed locally, will deploy soon. 
<img width="1267" alt="CleanShot 2023-06-07 at 19 39 58@2x" src="https://github.com/revsys/revsys-nuremberg/assets/144159/74aaba72-9624-4f5b-852e-585498a4d57a">
