### ISSUE TITLE
Full-text document search: missing snippet search results

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#242]
When doing full-text document search, search results sometimes missing snippet results

![full-text_document_highlighting_missing_in_snippet_search_results_3](https://github.com/revsys/revsys-nuremberg/assets/1544067/b65099eb-2893-40c9-aef9-fb008b33059d)

**Comment by frankwiles** [comment]
Appears to be fixed now. 
![CleanShot 2023-10-04 at 08 01 29](https://github.com/revsys/revsys-nuremberg/assets/144159/458f5513-fe5b-4600-b3a0-5373cf10f9ed)
