### ISSUE TITLE
Add content warning to landing page

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#244]
Content warning should be added to The Trials section of the landing page

![content_warning_draft](https://user-images.githubusercontent.com/1544067/230659742-81530403-7d01-4612-a5d2-afe5803ce380.jpg)

**Comment by frankwiles** [comment]
Done! 
<img width="1243" alt="CleanShot 2023-06-07 at 19 47 41@2x" src="https://github.com/revsys/revsys-nuremberg/assets/144159/f92663d8-e3ef-4648-bea5-0215dada69e4">
