### ISSUE TITLE
Full-text document retrieval failure from search results

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#245]
Unable to retrieve full-text document from search results

![document_retrieval_failure](https://user-images.githubusercontent.com/1544067/231000600-bc237aa4-18e7-4f12-b98d-dfbffbc4ebf1.jpg)

![document_retrieval_failure_2](https://user-images.githubusercontent.com/1544067/231000634-361e9869-6c32-47f8-80e0-098cf23dd4e6.jpg)

**Comment by frankwiles** [comment]
May be related to #249 year issue

**Comment by frankwiles** [comment]
Fixed and will deploy soon.
