### ISSUE TITLE
Document image-viewing area: auto-scrolling triggered by clicking in image area

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#248]
When user clicks within document's image-viewing area (including manipulating scrollbar), scrollbar begins to move down image-viewing area on its own

![auto_scrolling_in_doc_image_viewer](https://user-images.githubusercontent.com/1544067/232586681-8e22906f-b030-489c-9927-e8c2e40e0aa1.jpg)

**Comment by frankwiles** [comment]
Finally figured this out!

**Comment by pdeschner** [comment]
Super!

________________________________
