### ISSUE TITLE
Full-text document retrieval failure

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#250]
When user clicks on "Full-text View" link on document page, execution fails, generating error "We had a problem handling your request"

![full-text_document_retrieval_failure](https://user-images.githubusercontent.com/1544067/233170072-59ba6d4a-e921-4b15-a68a-d29656500888.jpg)

![full-text_document_retrieval_failure_2](https://user-images.githubusercontent.com/1544067/233170102-bbb781bc-bcbf-49ef-936a-afdb5ba578f6.jpg)

**Comment by frankwiles** [comment]
Verified this is no longer an issue. Click it returns: 

![CleanShot 2023-06-07 at 15 10 12](https://github.com/revsys/revsys-nuremberg/assets/144159/a554eafc-b7f3-4849-9d16-bec803b094a1)
