### ISSUE TITLE
Full-text document search-results snippets should be suppressed when not doing keyword search

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#253]
If user is doing fielded search only, search results for full-text documents should not include snippets

![full-text_documents_snippets_suppressed_if_not_keyword_search](https://user-images.githubusercontent.com/1544067/234371858-8864537d-324c-4e86-8241-bf6cbf80b958.jpg)

**Comment by nessita** [comment]
This is now fixed, available in the dev site.
