### ISSUE TITLE
Transcript page retrieval: discrepancy between page retrieved and page requested

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#265]
Transcript page retrieval: discrepancy between page retrieved and page requested -- this is working properly on legacy site:

![transcript_page_discrepancy_between_page_requested_and_page_retrieved](https://github.com/revsys/revsys-nuremberg/assets/1544067/8cb47f1d-6832-46bc-9f04-5e5f98af9872)

![transcript_page_discrepancy_between_page_requested_and_page_retrieved_2](https://github.com/revsys/revsys-nuremberg/assets/1544067/540ad408-19e2-42bc-816b-0d1f243a3279)

![transcript_page_links_off](https://github.com/revsys/revsys-nuremberg/assets/1544067/3b0ece08-a7e2-492f-ac12-79cef31cd51d)

**Comment by frankwiles** [comment]
This is the problem that isn't happening for Frank on Mac/Chrome but is happening for Paul on Windows and Mac (Chrome and Firefox)
