### ISSUE TITLE
Page images not displaying in document viewer

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#266]
When user clicks open document viewer in image-display mode, page images fail to display

![document_page_images_missing](https://github.com/revsys/revsys-nuremberg/assets/1544067/f96e1187-5083-4eeb-b60a-1afe452c0591)

**Comment by frankwiles** [comment]
It's definitely displaying now, not entirely sure why it wasn't for you previously. 
![CleanShot 2023-07-03 at 13 10 16](https://github.com/revsys/revsys-nuremberg/assets/144159/9fe861f2-286a-46fc-ad20-5ac509f7c6c3)

**Comment by pdeschner** [comment]
This is still not displaying for me on Windows 10 with Chrome and Firefox, and a MacBook Pro and Air with Chrome and Safari.

Thoughts?

Best,

Paul

________________________________

**Comment by frankwiles** [comment]
Hmmm ok I'm getting a CORS error in the JS console that might be causing your issue.  Weird that it works fine for me and Natalia.  She's on Firefox/Linux and I'm Chrome/Mac.

**Comment by frankwiles** [comment]
I believe I've figured this out @pdeschner can you confirm?

**Comment by pdeschner** [comment]
Yup -- looks good from here.

________________________________

**Comment by frankwiles** [comment]
Issue ended up being a debug setting that would have allowed it to ONLY work if you had a local running dev environment.  🤦‍♂️
