### ISSUE TITLE
Missing data point in document metadata display

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#269]
Metadata element displayed in search results listing but not in linked document metadata

![doc_metadata_missing_info](https://github.com/revsys/revsys-nuremberg/assets/1544067/b464f69e-f498-4f54-a63e-ada97d957114)

![doc_metadata_missing_info_2](https://github.com/revsys/revsys-nuremberg/assets/1544067/80f7b9af-6dbe-49a2-bc47-3f134eb0f4fd)

**Comment by frankwiles** [comment]
Fixed, HLSL is now a real Solr field and not assuming primary keys don't overlap.
