### ISSUE TITLE
Fielded search terms should not be highlighted in retrieved search items

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#280]
Fielded search terms should not be highlighted in retrieved search items

![fielded_search_terms_should_not_be_highlighted](https://github.com/revsys/revsys-nuremberg/assets/1544067/41388ada-4c9d-42b5-aec0-ac2c072a92bd)

**Comment by frankwiles** [comment]
Look into the frontend display of these results, Paul thinks Natalia did something there.
