### ISSUE TITLE
Highlighting seems to be turned off when on Transcript detail pages

### ISSUE THREAD

**Issue by frankwiles** [revsys/revsys-nuremberg#282]
If you search for "hitler" it shows for Document details: 

https://nuremberg.revsys.dev/documents/700-order-increasing-the-jurisdiction?mode=text&q=hitler

but not on Transcript pages: 

https://nuremberg.revsys.dev/transcripts/7-transcript-for-imt-trial-of-major-war-criminals?seq=7&q=hitler

**Comment by frankwiles** [comment]
Ask @nessita about this.  The template and view for Documents just passes the full text in, but for Transcripts the view/template combination constructs the joined html pages and I'm not sure where the highlighting is NOT happening and/or SHOULD be happening.

**Comment by frankwiles** [comment]
Example where not highlighting: http://localhost:8000/transcripts/7-transcript-for-imt-trial-of-major-war-criminals?seq=14&q=hitler
Example where is highlighting: http://localhost:8000/documents/700-order-increasing-the-jurisdiction?mode=text&q=hitler

**Comment by nessita** [comment]
> Ask @nessita about this. The template and view for Documents just passes the full text in, but for Transcripts the view/template combination constructs the joined html pages and I'm not sure where the highlighting is NOT happening and/or SHOULD be happening.

I'll check before the week ends and report back.

**Comment by nessita** [comment]
@frankwiles I can't reproduce this locally, I get all highlights showing just fine.

I tested the same thing on the dev site and in fact the highlights are not shown when the page is loaded, BUT, I disabled javascript using the developer console and the highlights appeared instantly.
