### ISSUE TITLE
Advanced search: add material- and search-type filters

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#289]
Advanced search: add material- and search-type filters (default: all boxes checked)

![advanced_search_material_and_search_type_filters](https://github.com/revsys/revsys-nuremberg/assets/1544067/42df8609-5cd1-4f5d-9f47-d6b135cf40b0)

Relates to #196

**Comment by frankwiles** [comment]
Have it display as two new rows with each item on the row.  So like: 

`Material Type:  X Documents X Transcripts X Photographs`
`Search Type: X Full-text X Description Information`

Put them first at the top. And have them checked by default.

**Comment by frankwiles** [comment]
Natalia estimates this is 2-3 days of work for the Full Text vs Metadata search

**Comment by frankwiles** [comment]
Paul is checking to see if this is ok to go forward with.

**Comment by frankwiles** [comment]
Paul approved this work so you can get started @nessita

**Comment by nessita** [comment]
@pdeschner Hi! Before working on this feature, I wanted to confirm a few things with you since in order to make this new search type works, I need to make some changes to the Solr index. So, following this full-text spec sentence:

> If a document has both full-text and metadata versions, we would like to treat them as separate search-result hits in the same listing.

and using this example for better understanding:

There is a document full-text "x" with 3 matching images, let's call them "a", "b", "c". When doing a search for a term "t" that has matches both in metadata and full text, should a normal search include the 4 items in the results? This would be 4 rows with x, a, b and c. The row for "x" would have the "full text" label while the 3 rows for a, b, and c, would not.

Now, for the advanced search: when searching for the term "t", is the default behavior to include results for all x, a, b, and c?
And then if the user selects "full-text", do we only return "x"? and if the user selects "descriptive information", we'd only return a, b and c?

Is the above correct? If yes, could you please confirm that we won't have search results rows that combine full-text with metadata in the same row?

Thanks!

**Comment by pdeschner** [comment]
Hi Natalia,

Greetings!  Thanks for the request for clarification -- I've answered your questions inline below.

Please get back with any questions if any of this is unclear -- I may well have missed something in thinking this through.

Many thanks!

Paul


________________________________

**Comment by pdeschner** [comment]
Also, if it should prove too difficult to add links for both "[Text] [Image]" to the entries in the search results, then it would be okay to simply list the primary link alone -- either "[Text]" or "[Image]" depending on whether the search result is for a full-text match (when "[Text]" would be displayed) or for a metadata (aka "descriptive information") match (when "[Image]" would be displayed).

When returning search results for the non-document material types -- i.e., transcripts and/or photographs -- then please display a "[Text]" link for transcripts and an "[Image]" link for photographs.

Happy to answer any questions, if this is unclear.

**Comment by nessita** [comment]
@pdeschner @frankwiles Question regarding extending the search with the "search type". Would it make a bit more sense to just grow material type to differentiate between document text and document metadata? This way, we wouldn't have two listings (material type and search type) and the user would be presented with, IMHO, a better UI/UX:

[ ] Document transcripts
[ ] Document metadata
[ ] Trial Transcripts
[ ] Photographs

What do you think?

**Comment by pdeschner** [comment]
Hey Natalia,

So, it's certainly an interesting suggestion, but I think we'll want to stick with the 2 typologies:

  1.  Material Type: Document, Transcript, Photograph
  2.  Search Type: Full Text, Descriptive Information

This also follows a number of mainline archival sites, which keep search type distinct.  It also maintains a clean conceptual separation, which I think is very useful in a collection as complex as ours.

Cheers,

Paul


________________________________

**Comment by nessita** [comment]
> This also follows a number of mainline archival sites, which keep search type distinct. It also maintains a clean conceptual separation, which I think is very useful in a collection as complex as ours.

Thank you Paul for the answer. Now, follow up question:

 * Would Full Text match both document full texts and trial transcripts? (just like the new tag-like we added [Text] for both of them)
 * And then, would Descriptive Information match photographs as well? Or just document images?

**Comment by nessita** [comment]
A bit more context for my question, we should define the behavior of someone choosing a combination of:

* material type `photograph` and any of the search types
* material type `transcript` and any of the search types

**Comment by pdeschner** [comment]
Hi Natalia,

So, I think I've completely overlooked one aspect of our new search type + material type regime: the user would be able to select a combination of material type and search type in which search and material would be incompatible -- such as search type of full text and material type of photographs, or search type of descriptive information and material type of transcript.

So, I think your suggestion below might actually be the best way to resolve this, short of having the app issue an error message to the user they select an invalid search + material type combo.

The four search combos would be:

  1.  Document full text
  2.  Document descriptive information
  3.  Trial transcript full text
  4.  Photograph descriptive information

The default would be for them all to be selected, and it would eliminate the need to maintain 2 separate category types (material as well as search type).  I would label the combos "Search Type" rather than "Material Type" since we're asking the user to tell us what kind of search they would like to execute, which includes within it material type.

This also nicely documents for the user at a single glance our site's content types and means of accessing each.

Does that make sense, and does this answer your other questions?

Thanks,

Paul


________________________________

**Comment by nessita** [comment]
> Does that make sense, and does this answer your other questions?

It does, and yes, this answers my questions. For the record, I think this is the nicest solution UI/UX wise. Thanks!

**Comment by nessita** [comment]
I believe this is now implemented and available in the dev site, though we still need to fully reindex Solr for the code changes to work as expected. @frankwiles any chance you could trigger a reindex?
