### ISSUE TITLE
Advanced search: enable multi-author picklist

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#290]
Advanced search: enable multi-author picklist

![is_it_possible_to_designate_multiple_authors_in_advanced_search_picklist pg](https://github.com/revsys/revsys-nuremberg/assets/1544067/9423e4c0-f612-467d-9453-0ccff9e45c46)

![no_way_to_designate_multiple_authors_in_advanced_search pg](https://github.com/revsys/revsys-nuremberg/assets/1544067/480e7df2-63bd-457f-b358-3980e8a23c40)

**Comment by frankwiles** [comment]
Move this to react so we can use react-select2 in a multi-select format. If you can do it with jquery do it.

**Comment by frankwiles** [comment]
@nessita will verify the backend is ready for multiple authors
