### ISSUE TITLE
Full-text docs: some docs incorrectly identified as full-text docs in search-results listing

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#302]
When user clicks on some full-text docs, no full text is retrieved (just a blank screen where the full text should appear)

![false_full-text_doc_designation](https://github.com/revsys/revsys-nuremberg/assets/1544067/5531f52c-96da-4c77-a19e-2186973f978d)

![missing_full-text_doc_content_in_doc_viewer](https://github.com/revsys/revsys-nuremberg/assets/1544067/fce99fb6-f21b-4723-823f-86c757a2af4d)

**Comment by frankwiles** [comment]
Detail page of the document in question that is bad https://nuremberg.revsys.dev/documents/2510-translation-of-document-uk-81?mode=search-text&q=%22hitler+said%22

**Comment by nessita** [comment]
Sorry about this, it's now fixed in https://github.com/revsys/revsys-nuremberg/commit/dbf41b5ac7442c0deb479e65ac19eae7fa70dc33 (currently being deployed to the dev site)
