### ISSUE TITLE
Full-text document view missing keyword search-term highlighting

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#303]
Full-text document view missing keyword search-term highlighting

![full-text_document_view_highlighting_of_keyword_search_terms_missing](https://github.com/revsys/revsys-nuremberg/assets/1544067/6579cd97-9bb3-4ec2-8a12-b4459d58ad81)

**Comment by nessita** [comment]
Fixed in https://github.com/revsys/revsys-nuremberg/commit/c8c51856335fb94f8ad95c8dc01c58ccc8f50d5d, it's being deployed to dev now.
