### ISSUE TITLE
Transcript keyword snippets and highlighting working on old site but not on new site: screenshot comparison

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#309]
Transcript keyword snippets and highlighting working on old site but not no new site: screenshot comparison

![transcript_search_legacy_snippets_correct](https://github.com/revsys/revsys-nuremberg/assets/1544067/4806674c-deb7-405b-b854-40b136b3e4a3)

![transcript_search_legacy_snippets_correct_2](https://github.com/revsys/revsys-nuremberg/assets/1544067/e8b56ebf-1d34-4d9c-ad08-3cef60785ce3)

![transcript_search_legacy_page_highlighting_correct](https://github.com/revsys/revsys-nuremberg/assets/1544067/dd6220c7-5cb9-4e87-8371-3bc71955d132)

![transcript_search_new_snippets_no_highlighting](https://github.com/revsys/revsys-nuremberg/assets/1544067/ff5ce5ad-3f6f-4c2b-a98c-882c24b89f3b)

![transcript_search_new_snippets_no_highlighting_2](https://github.com/revsys/revsys-nuremberg/assets/1544067/e4def308-1b96-45ab-af6e-67ed33928c23)

![transcript_search_new_page_no_highlighting](https://github.com/revsys/revsys-nuremberg/assets/1544067/f1e6b9e1-6575-42a5-9b72-60d340891951)

**Comment by frankwiles** [comment]
@nessita thinks it MAY (but not necessarily) but related to the change from old to new Solr [here](https://github.com/revsys/revsys-nuremberg/pull/254/files#diff-2839fdafcb881cf0587d1822da1a2da8f718d14455b9a067eff7a9691df9ab01)

**Comment by nessita** [comment]
Fixed after reverting changes to Solr highlighting method (reverted method from `unified` to `original`).

**Comment by frankwiles** [comment]
Works in the first page of results and the list of Transcript pages, but NOT on the detail page itself. 

Shows: https://nuremberg.revsys.dev/transcripts/1-transcript-for-nmt-1-medical-case/search?q=euthanasia
Doesn't show: https://nuremberg.revsys.dev/transcripts/1-transcript-for-nmt-1-medical-case?seq=73&q=euthanasia
