### ISSUE TITLE
Advanced search picklist items styling: use same styling as in other advanced-search picklists

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#315]
Advanced search picklist items styling: use same styling as in other advanced-search picklist

![advanced_search_author_picklist_normative](https://github.com/revsys/revsys-nuremberg/assets/1544067/1217ce3c-f2e2-475b-a21c-a20a71eb2714)

**Comment by frankwiles** [comment]
I was ablet to get things closer, but not exactly the same due to how the multiple choice needs to work.

**Comment by frankwiles** [comment]
Fix font to be "Proof"

**Comment by pdeschner** [comment]
Still not seeing sans serif font on Mac and Windows Chrome, but am seeing it on Windows Firefox.  Selected authors not in sans serif on Windows Firefox.

________________________________
