### ISSUE TITLE
Add "Search in Transcript" buttons to right of search box on transcript search-results snippets page and transcript text-display pages

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#327]
Add "Search in Transcript" buttons to right of search box on transcript search-results snippets page and transcript text display pages

![search_in_transcript_button](https://github.com/revsys/revsys-nuremberg/assets/1544067/9e9c637a-5b65-4abc-9b39-b7a630baad40)

![search_in_transcript_button_2](https://github.com/revsys/revsys-nuremberg/assets/1544067/d9e3d517-9815-4dc8-b851-6f4f24b3e61e)

**Comment by frankwiles** [comment]
Done, but not quite deployed yet. Will be a few minutes.
