### ISSUE TITLE
Non-transcript docs not loading

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#332]
Non-transcript docs not loading

![non-transcript_docs_not_loading](https://github.com/revsys/revsys-nuremberg/assets/1544067/a28dfc8d-c51a-4023-b6cf-8c6d664e4f01)

![image_doc_not_loading](https://github.com/revsys/revsys-nuremberg/assets/1544067/11b6eefc-4dd8-4100-a522-818aa5c234df)

**Comment by frankwiles** [comment]
Yep I screwed up in the last deploy, fixing it now.
