### ISSUE TITLE
Executed search information missing materials-type domain when executing global search from landing page

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#335]
Executed search information missing materials-type domain when executing global search from landing page

![search_domain_missing](https://github.com/revsys/revsys-nuremberg/assets/1544067/58711743-ee6c-4b20-b4df-ba1e052c6efe)

![search_domain_indicated](https://github.com/revsys/revsys-nuremberg/assets/1544067/4e5898aa-0bb3-43a9-9eef-5adff854afd7)

**Comment by frankwiles** [comment]
If it's not overridenn, just show the additional `document full text|....`

**Comment by frankwiles** [comment]
Add 'All documents' if they don't search anything 
<img width="1558" alt="CleanShot 2023-09-27 at 13 16 13@2x" src="https://github.com/revsys/revsys-nuremberg/assets/144159/772ab69f-1147-4581-b22f-ed5dfbae1b83">
