### ISSUE TITLE
Search-results page: date facet year-range indicator not retaining requested dates

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#344]
Search-results page: date facet year-range indicator not retaining requested dates

![date_facet_not_working](https://github.com/revsys/revsys-nuremberg/assets/1544067/ca94d774-8561-423a-b54f-14d0569e1547)

![date_facet_not_working_2](https://github.com/revsys/revsys-nuremberg/assets/1544067/543c51e0-ab3c-439c-9d13-6972a1fc79e8)

**Comment by frankwiles** [comment]
This should be fixed as well, just forgot to close it.
