### ISSUE TITLE
Add several metadata fields to full-text documents

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#346]
Add the following metadata fields to full-text documents to allow limited metadata search on full-text documents:
1. Author (both Personal Authors and Group Authors)
2. Date
3. Evidence File Code

**Comment by frankwiles** [comment]
Note to self: "Evidence File Code" is the same as the field/label on Advanced Search page.

**Comment by nessita** [comment]
> Add the following metadata fields to full-text documents to allow limited metadata search on full-text documents:
> 
>     1. Author (both Personal Authors and Group Authors)
> 
>     2. Date
> 
>     3. Evidence File Code

Hey @pdeschner, I'm working on this. From our implementation, I already see evidence codes being indexed for each full-text document. Is there an example of a search result where an expected evidence code is missing? Thank you!

**Comment by pdeschner** [comment]
Hi Natalia, I didn't realize evidence codes were already being included as metadata for full-text documents.  And, no, I haven't so far found any examples of full-text docs with missing evidence codes.  Thanks!  Paul

________________________________
