### ISSUE TITLE
Photographs: download-image link not working

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#350]
Photographs: download-image link not working (working on legacy site)

![photographs_download_image_link_not_working_2](https://github.com/revsys/revsys-nuremberg/assets/1544067/8f60fd8f-5b8e-47d1-b47e-a9048fb32d78)

![photographs_download_image_link_not_working](https://github.com/revsys/revsys-nuremberg/assets/1544067/d83b9502-cae9-4baa-8f42-5fe35bba05a6)

**Comment by frankwiles** [comment]
Fix URL to be `https` and not `http`

**Comment by frankwiles** [comment]
@pdeschner can you confirm this one is fixed now?
