### ISSUE TITLE
Safari browser: images for Photographs material type only appear as thumbnails instead of full-size (as in Chrome and Firefox)

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#355]
Safari browser: images for Photographs material type only appear as thumbnails instead of full-size (as in Chrome and Firefox)

![safari_thumbnail_photos](https://github.com/revsys/revsys-nuremberg/assets/1544067/9662c6f2-06ee-498a-bbc6-62157c84d2f9)

**Comment by frankwiles** [comment]
Think this happened while I had the object storage broken.
