### ISSUE TITLE
Advanced search defendants' and authors' names not aligned with author and defendant names for simple search and faceting, resulting in search failures

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#367]
Advanced search defendants' and authors' names not aligned with author and defendant names for simple search and faceting, resulting in search failures

![advanced_search_defendant_picklist_error](https://github.com/revsys/revsys-nuremberg/assets/1544067/a941a183-dedf-4493-8347-1ef484c43684)

![advanced_search_defendant_picklist_error_2](https://github.com/revsys/revsys-nuremberg/assets/1544067/3fd7f850-4684-420d-ae0f-ca9a828765c2)

![advanced_search_author_picklist_error](https://github.com/revsys/revsys-nuremberg/assets/1544067/fee7a300-a697-47de-951a-e195e99dca78)

**Comment by frankwiles** [comment]
Defendant in select is just `name` and search_index is full_name, but it's more complicated because of the data relationships.  The Author issue is related to the "Group" authors and not individual authors is just using the wrong name.
