### ISSUE TITLE
Multi-select in advanced search

### ISSUE THREAD

**Issue by frankwiles** [revsys/revsys-nuremberg#380]
Can you fill in exactly how you want these to work?

**Comment by pdeschner** [comment]
Implement multi-select fields on Advanced Search page:
1. Author (already done)
2. Defendant
3. Trial Issues
4. Trial
5. Language
6. Source

These should all be implemented as the Author picklist is currently: with multiple items selectable by the user, with items vertically listed and allowing the user de-select individual items from the currently selected list by clicking on the "x" to the left of the item name.

![advanced_search_multi-select_fields](https://github.com/revsys/revsys-nuremberg/assets/1544067/8e702f13-baff-4707-a070-bfbe675371d2)

**Comment by frankwiles** [comment]
@pdeschner ok this is live on the site.  Can you check it over for me please? I did a few successful searches that seem to work, but on some items like Trial I'm not finding any documents that span two of them easily and hoping you just know of some.
