### ISSUE TITLE
Improve sure document text's viewport

### ISSUE THREAD

**Issue by nessita** [revsys/revsys-nuremberg#39]
For example, doc https://nuremberg.revsys.dev/documents/483-cross-reference-for-document-ps?mode=text shows how the text viewport is not contained to a fixed height. We should make this section has a fixed height and have the text inside it be scroll-able.

**Comment by frankwiles** [comment]
Going to double check with Paul next week that he really wants that.  I can see it both ways.  If we mess with the scroll area some readers and tools can't resume back to the same location.  Not a huge deal either way.

**Comment by frankwiles** [comment]
Emailed Paul asking for the answer.

**Comment by frankwiles** [comment]
Paul wants to leave it as is.
