### ISSUE TITLE
Adjust multiselect OR options

### ISSUE THREAD

**Issue by frankwiles** [revsys/revsys-nuremberg#391]
- [x] Make trial, defendant, languages, source.  These make no sense as ANDs, make them ORs when multiselect.  
- [x] Add toggle option for Author, Trial issue to allow the user to pick `AND` or `OR` searching. Place toggle to the left 
- [x] Swap vertical position of Defendant and Trial Issue so that the ORs are all together
- [x] Add help text above the OR options to let the user know these are ORs and it makes no sense to AND them
- [x] Adjust visual look to be roughly this in terms of layout/structure.  Text and exact design TBD

![CleanShot 2024-02-01 at 14 50 17](https://github.com/revsys/revsys-nuremberg/assets/144159/9b19a0e4-6946-4113-9b26-ee08d28627a6)

**Comment by pdeschner** [comment]
See following mock-up for wording and placement of multi-select labels:

![test](https://github.com/revsys/revsys-nuremberg/assets/1544067/f0c05a58-c3de-485a-b9d0-bf5dfa6d6d84)

**Comment by frankwiles** [comment]
For our meeting today, we don't really have room to do this with some of these select boxes: 

![CleanShot 2024-02-29 at 10 26 12](https://github.com/revsys/revsys-nuremberg/assets/144159/8988089b-d7aa-49f2-916f-3e9c26c8c6fc)

**Comment by frankwiles** [comment]
But if we do it this way it fits more easily

![CleanShot 2024-02-29 at 10 27 17](https://github.com/revsys/revsys-nuremberg/assets/144159/0d76a6fa-8e16-45e1-9798-cad0115b22b1)

**Comment by pdeschner** [comment]
That looks good to me.

Thanks,

Paul

________________________________

**Comment by frankwiles** [comment]
Fixed another small issue here we were still saying "Choose one or more..." 

![CleanShot 2024-02-29 at 10 28 56](https://github.com/revsys/revsys-nuremberg/assets/144159/c4d5d92f-6815-4950-b9c7-5427153cfbcf)
