### ISSUE TITLE
PDF document download feature broken

### ISSUE THREAD

**Issue by pdeschner** [revsys/revsys-nuremberg#407]
PDF document download feature broken:
1. Only a single page of a multi-page document is selected and then duplicated as many times as there are pages in the document, instead of retrieving each discrete page of the document
2. It is also not possible to use the subset page-range feature to download only a single page or some subset of pages -- the same random page is selected and (if more than one page was selected for download) duplicated in the resulting PDF
3. The initial page of the PDF is blank instead of displaying metadata about the document

Both these features are functioning properly in the legacy app.

![document_page_pdf_download_broken](https://github.com/revsys/revsys-nuremberg/assets/1544067/74d6c56a-6df0-4608-b583-51218f4c166e)

See attached documents for reference (same 30-page document in each case: hlsls ID no. 15):
1. One from new app
2. One from legacy app

[HLSL Nuremberg Document #15 pages 1-30_legacy_app.pdf](https://github.com/revsys/revsys-nuremberg/files/15340267/HLSL.Nuremberg.Document.15.pages.1-30_legacy_app.pdf)
[HLSL Nuremberg Document #15 pages 1-30_revsys_app.pdf](https://github.com/revsys/revsys-nuremberg/files/15340268/HLSL.Nuremberg.Document.15.pages.1-30_revsys_app.pdf)

**Comment by frankwiles** [comment]
Ok I've figured out the front page metadata piece this morning, but I haven't yet figured out the repeating PDF image issue. Still digging.

**Comment by pdeschner** [comment]
Thanks!

________________________________

**Comment by frankwiles** [comment]
Ok I was able to figure it out! Weird variable scoping issue I introduced when moving it from Backbone to vanilla JS.  New version is building now.

**Comment by pdeschner** [comment]
Super – many thanks!

________________________________

**Comment by frankwiles** [comment]
Ok it's live now and definitely fixed, example PDF
[HLSL Nuremberg Document #694 pages 1-25 (1).pdf](https://github.com/user-attachments/files/15871749/HLSL.Nuremberg.Document.694.pages.1-25.1.pdf)
